project:
  type: website
  output-dir: ../docs

website:
  title: "Tyler D. Wiederich"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

