project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Tyler Wiederich"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - presentations.qmd
      - href: blog/index.qmd
        text: "#TidyTuesday"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    respect-user-color-scheme: true
    



