---
title: "Projects"
---

## Evaluating Perceptual Judgements on 3D Printed Bar Charts

Studies show that people make less accurate judgements when comparing values in a 3D graph than its corresponding 2D graph. However, these studies almost entirely consist of projecting the 3D graphs onto paper or on screens (which are 2D surfaces). The goal of this study is to bring 3D graphs into a 3-dimensional environment via 3D printing.

This project is currently ongoing with my advisor, Susan VanderPlas. Preliminary results will be presented at SDSS in 2023, with future integration into experiential learning for an introductory statistics course at UNL.

## Photopal

As part of the requirement of STAT 892, we were tasked with creating an R package. My group and I designed a package that creates color palettes from images. The main feature is creating a palette from an image input, but it also includes the functionality of creating a colorblind-safe palette. You can try it out here!

```{r, eval=FALSE}
devtools::install_github('Hiiiua/Photopal')
```

